services:
  - type: web
    name: rdvapp
    env: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: |
      npm ci --include=dev
      npm run build
      npx prisma generate
    startCommand: npm run start:server
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: VITE_API_URL
        value: /api
      - key: DATABASE_URL
        fromDatabase:
          name: rdvapp-db
          property: connectionString
      - key: BASE_URL
        fromService:
          type: web
          name: rdvapp
          property: url
    healthCheckPath: /api/health
    autoDeploy: true
    domains:
      - rdvapp.example.com

  - type: redis
    name: rdvapp-cache
    plan: free
    maxmemoryPolicy: noeviction
    region: frankfurt  # You can change this to your preferred region
    ipAllowList: [] # Only allow internal connections

databases:
  - name: rdvapp-db
    plan: free
    postgresMajorVersion: 15
    ipAllowList: [] # Only allow internal connections
